import StreamVideoProvider from "@/providers/StreamClientProvider";
import { Metadata } from "next";
import React, { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Video Chat",
  description: "Video Calling App ... Generated by Mohanad Hassan",
  icons: {
    icon: '/icons/logo.svg'
  }
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <main>
      <StreamVideoProvider>
        {/* <div className="relative w-full h-screen flex flex-col items-center justify-center">
          {children}
        </div> */}
        {children}
      </StreamVideoProvider>
    </main>
  );
};

export default RootLayout;
